"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserKeys = void 0;
var UserKeys;
(function (UserKeys) {
    UserKeys["AllowsDailyNotification"] = "allowsDailyNotification";
    UserKeys["CompletedModules"] = "completedModules";
    UserKeys["CurrentModuleItem"] = "currentModuleItem";
    UserKeys["DailyNotificationMinute"] = "dailyNotificationMinute";
    UserKeys["IsActive"] = "isActive";
    UserKeys["IsOnboarding"] = "isOnboarding";
    UserKeys["JoinedMembersGroupAt"] = "joinedMembersGroupAt";
    UserKeys["LastDailyNotificationSentAt"] = "lastDailyNotificationSentAt";
    UserKeys["LastStreakActivityAt"] = "lastStreakActivityAt";
    UserKeys["LastTickAt"] = "lastTickAt";
    UserKeys["ModuleCursor"] = "moduleCursor";
    UserKeys["NextDailyNotificationAt"] = "nextDailyNotificationAt";
    UserKeys["NextTickAt"] = "nextTickAt";
    UserKeys["StreakCount"] = "streakCount";
    UserKeys["TelegramLinkKey"] = "telegramLinkKey";
    UserKeys["TelegramId"] = "telegramId";
    UserKeys["TelegramFirstName"] = "telegramFirstName";
    UserKeys["TelegramLastName"] = "telegramLastName";
    UserKeys["Timezone"] = "timezone";
    UserKeys["UscreenUserId"] = "uscreenUserId";
    UserKeys["UscreenCountry"] = "uscreenCountry";
    UserKeys["UscreenEmail"] = "uscreenEmail";
    UserKeys["UscreenNickname"] = "uscreenNickname";
    UserKeys["UscreenName"] = "uscreenName";
})(UserKeys = exports.UserKeys || (exports.UserKeys = {}));
//# sourceMappingURL=user.js.map