"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StatsKeys = exports.UserModuleKeys = exports.UserKeys = void 0;
var UserKeys;
(function (UserKeys) {
    UserKeys["AirtableId"] = "airtableId";
    UserKeys["AllowsDailyNotification"] = "allowsDailyNotification";
    UserKeys["CompletedModules"] = "completedModules";
    UserKeys["DailyItemId"] = "dailyItemId";
    UserKeys["DailyNotificationMinute"] = "dailyNotificationMinute";
    UserKeys["Id"] = "id";
    UserKeys["IsActive"] = "isActive";
    UserKeys["JoinedMembersGroupAt"] = "joinedMembersGroupAt";
    UserKeys["LastDailyNotificationSentAt"] = "lastDailyNotificationSentAt";
    UserKeys["LastStreakActivityAt"] = "lastStreakActivityAt";
    UserKeys["LastTickAt"] = "lastTickAt";
    UserKeys["Module"] = "module";
    UserKeys["Phone"] = "phone";
    UserKeys["RegisteredForSquadAt"] = "registeredForSquadAt";
    UserKeys["StreakCount"] = "streakCount";
    UserKeys["StartDate"] = "startDate";
    UserKeys["Stats"] = "stats";
    UserKeys["TelegramFirstName"] = "telegramFirstName";
    UserKeys["TelegramId"] = "telegramId";
    UserKeys["TelegramLastName"] = "telegramLastName";
    UserKeys["TelegramLinkKey"] = "telegramLinkKey";
    UserKeys["TelegramSmallGroupId"] = "telegramSmallGroupId";
    UserKeys["TelegramSmallGroupUrl"] = "telegramSmallGroupUrl";
    UserKeys["Timezone"] = "timezone";
    UserKeys["UscreenUserId"] = "uscreenUserId";
    UserKeys["UscreenCountry"] = "uscreenCountry";
    UserKeys["UscreenEmail"] = "uscreenEmail";
    UserKeys["UscreenNickname"] = "uscreenNickname";
    UserKeys["UscreenName"] = "uscreenName";
})(UserKeys = exports.UserKeys || (exports.UserKeys = {}));
var UserModuleKeys;
(function (UserModuleKeys) {
    UserModuleKeys["ModuleId"] = "moduleId";
    UserModuleKeys["ModuleItemId"] = "moduleItemId";
    UserModuleKeys["StartStep"] = "startStep";
    UserModuleKeys["StartTimestamp"] = "startTimestamp";
    UserModuleKeys["FurthestStep"] = "furthestStep";
})(UserModuleKeys = exports.UserModuleKeys || (exports.UserModuleKeys = {}));
var StatsKeys;
(function (StatsKeys) {
    StatsKeys["StreakCount"] = "streakCount";
    StatsKeys["WatchTime"] = "watchTime";
    StatsKeys["WatchCount"] = "watchCount";
})(StatsKeys = exports.StatsKeys || (exports.StatsKeys = {}));
//# sourceMappingURL=user.js.map